### ISSUE TITLE
Charaktere filtern

### ISSUE THREAD

**Issue by SebastianSchmidt** [SebastianSchmidt/plotify#10]
Als Schriftsteller/in möchte ich die Charaktere meiner Geschichte über einen Suchbegriff filtern, um einzelne Charaktere schneller zu finden.

Akzeptanzkriterien:

- [x] Ein Charakter wird dann in der Ergebnisliste angezeigt, wenn der Suchbegriff unabhängig von der Groß- und Kleinschreibung in dem Namen des Charakters enthalten ist.

**Comment by itsJASPERr** [comment]
#9
