### ISSUE TITLE
Größe und Position des Hauptfensters

### ISSUE THREAD

**Issue by SebastianSchmidt** [SebastianSchmidt/plotify#13]
Als Schriftsteller/in möchte ich, dass die Software beim Starten das Hauptfenster mit der gleichen Größe und Position wie beim letzten Verwenden der Software anzeigt.

**Comment by SebastianSchmidt** [comment]
Die folgenden Informationen über das Hauptfenster sollen beim Beenden der Software gespeichert und beim nächsten Start wiederhergestellt werden:

- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by SebastianSchmidt** [comment]
Unter Ubuntu 16.10 und Linux Mint 18.1 tritt folgender Fehler auf: Die y-Position wird um ca. 30 Pixel erhöht, so dass der Fenster etwas verschoben gestartet wird. Die anderen Werte werden korrekt gesetzt.

**Comment by itsJASPERr** [comment]
Bei Windows 10 keine Probleme.

**Comment by SebastianSchmidt** [comment]
Da der Fehler nur unter Linux auftritt schließe ich das Ticket erst einmal. Für den Fehler unter Linux habe ich ein eigens Ticket #16 erstellt.
