### ISSUE TITLE
Designkonzept (Name, Logo, Farben)

### ISSUE THREAD

**Issue by itsJASPERr** [SebastianSchmidt/plotify#2]
InGRESS
ASTOR    Awesome STORy
CREST    CREating STory
CREASE    CREating Awesome StoriEs
dIGS    I Got Story
MASON  my awesome story
CASIA  creating awesome stories
GUESS  Greate Stories
CATSUIT  Creating Awesome Story Tool😆
CRACkERS    CReating Awesome CharactERs  Story
WITTY    WrITer TYpography

**Comment by SebastianSchmidt** [comment]
Der Name und das grobe Farbkonzept steht mittlerweile fest.
Am Logo wird noch gearbeitet.

**Comment by SebastianSchmidt** [comment]
Das Logo für die erste Version ist final.
