### ISSUE TITLE
Speicherort einer Geschichte öffnen

### ISSUE THREAD

**Issue by SebastianSchmidt** [SebastianSchmidt/plotify#30]
Als Schriftsteller/in möchte ich den Speicherort einer Geschichte öffnen, damit ich mit der Datei, in der die Geschichte gespeichert ist, arbeiten kann.

**Comment by SebastianSchmidt** [comment]
Funktioniert unter Ubuntu 16.10.

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Test unter Windows 10

**Comment by itsJASPERr** [comment]
Funktioniert unter Windows 10
